version: '3.8'

services:
  mysql:
    container_name: sample_db
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - sample_db_data:/var/lib/mysql
      - "./db/my.cnf:/etc/my.cnf"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"

  adminer:
    container_name: sample_db_adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  sample_db_data:
